# Generated by Django 6.0.3 on 2026-03-31 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='otpverification',
            name='failed_attempts',
            field=models.IntegerField(default=0),
        ),
    ]
